### PR TITLE
Translate ja

### PR DESCRIPTION
**Pull request by kazunito**
Translate to Japanese

### CODE REVIEW

**Comment by bjoernricks** [comment]
Thanks a lot for your translations! I really appreciate that. We are using pootle platform at https://translate.greenbone.net/ for the translations. Translating the master branch is a bit difficult at the moment because all stuff isn't settled yet. Therefore the pot file at https://translate.greenbone.net/ isn't up to date and things are getting out of sync from time to time. Nevertheless I'll try to integrate your po file.
 
Maybe you can create an account at https://translate.greenbone.net/ too

**Comment by janowagner** [comment]
I assume this is the file create at and downloaded from the translation platform.
The pull request simply needs to refer to the "gsa-7.0" branch instead of "master".

**Comment by bjoernricks** [comment]
Yeah I after looking at the actual po file I suppose something is mixed up. Your commit adds jp translations to the master branch (will be GSA 8.0 in future and is a complete rewrite) and po file for the gsa-7.0 branch.

**Comment by bjoernricks** [comment]
Just saw your changes at https://translate.greenbone.net/ja/
Both po files needs to be added to https://github.com/greenbone/gsa/tree/gsa-7.0

**Comment by kazunito** [comment]
I pull requested gsa - 7.0 correspondence at # 874.

**Comment by bjoernricks** [comment]
I'll close this pr in favor for #874

**Pull request closed without merging**
