### PR TITLE
Change the HTML Tag of detection method to Preformatted

### PR DESCRIPTION
**Pull request by y0urself**
**What**:

* Change the HTML Tag of Detection Method to Preformatted, so it does not remove the newlines ...

image

**Why**:

* Was badly formatted before ...

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

### CODE REVIEW

**Review by swaterkamp — APPROVED** [review]

**Review by bjoernricks — CHANGES_REQUESTED** [review]
Please please add a test for this change. I know it can be cumbersome for this small change but we need to ensure not to break this formatting in future accidentally.

**Comment by y0urself** [comment]
> Please please add a test for this change. I know it can be cumbersome for this small change but we need to ensure not to break this formatting in future accidentally.

Sorry I missed to do this a draft ... was not ready!

**Comment by y0urself** [comment]
> Please please add a test for this change. I know it can be cumbersome for this small change but we need to ensure not to break this formatting in future accidentally.

The merged test from https://github.com/greenbone/gsa/pull/2794 should cover these lines.

**Review by bjoernricks — APPROVED** [review]
I don't see a test that checks the formatting of the test but nevertheless this PR should be merged now.

**Comment by cfi-gb** [comment]
Fixes: #427

**Pull request merged**
