### PR TITLE
Fix setting comments of BPM nodes

### PR DESCRIPTION
**Pull request by swaterkamp**
**What**:
Fix setting comments of BPM nodes.

**Why**:
The correct value in the textfield wasn't shown and got overwritten by each single key press.

**How**:
Create a node with a proper comment and edit a node's comment. In both cases the current comment value was shown to the user and after clicking save it was applied to the node.

**Checklist**:

- [N/A] Tests
- [X] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

### CODE REVIEW

**Review by bjoernricks — COMMENTED** [review]
I would love to see a test for this.

**Comment by swaterkamp** [comment]
Afaik we don't have a testing concept for dialogs, yet.

**Review by bjoernricks — APPROVED** [review]
I am feeling not very well approving this PR without a test.

**Comment by swaterkamp** [comment]
I'll think about how to test dialogs today. There might be something like a prototype for that in master.

**Pull request merged**
