### PR TITLE
Migrate license headers to new template and update year of last modification

### PR DESCRIPTION
**Pull request by davidak**
In 2 places the script has also updated the copyright line. (footer and about)

Please review if that's in your interest.

### CODE REVIEW

**Comment by davidak** [comment]
> Shouldn't the new headers include 2019?

This PR only migrates the license headers to the new template. Updating the date of last modification is another task i work on.

**Comment by swaterkamp** [comment]
I just thought it could be done in one PR, as you are touching more than 940 files anyway. But go ahead :)

**Comment by davidak** [comment]
@swaterkamp if it's easier for you to review i can add it to this PR.

**Comment by swaterkamp** [comment]
That way all headers have to be "reviewed" only once instead of twice (once for the new template, and once whether the year got updated).

**Comment by davidak** [comment]
OK, i will do so. The year is updated after the last change from git. Not every file was updated in 2019.

**Comment by bjoernricks** [comment]
We tend to update all headers to 2019 because the copyright for the new year is still valid. It doesn't end in the last year when being touched.

**Comment by davidak** [comment]
I also updated the year. Please note the new PR description!

**Comment by swaterkamp** [comment]
The changes in About and Footer are definitely in our interest. Thanks!

**Pull request merged**
