### PR TITLE
Actions for all branches | Drop CircleCI

### PR DESCRIPTION
**Pull request by bjoernricks**
**What**:

Prepare workflow files for using them in all branches. We need to backport the files to the branches afterwards.

**Why**:

We want to use github actions for all branches.

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry
- [ ] Labels for ports to other branches

### CODE REVIEW

**Comment by y0urself** [comment]
Thx for taking over this!

**Review by y0urself — DISMISSED** [review]

**Comment by y0urself** [comment]
@bjoernricks I am actually not sure if we should set `path` in the workflows ...
When we require a workflow, that will never be triggered because the code in the set `path` has not been changed, the check will never complete.
(At least I think that it is the problem here ...)

**Comment by bjoernricks** [comment]
> @bjoernricks I am actually not sure if we should set `path` in the workflows ...
> When we require a workflow, that will never be triggered because the code in the set `path` has not been changed, the check will never complete.
> (At least I think that it is the problem here ...)

I really thought github would be intelligent enough to get that right. We really need to think about splitting gsad and gsa into two separate repos.

**Comment by y0urself** [comment]
> > @bjoernricks I am actually not sure if we should set `path` in the workflows ...
> > When we require a workflow, that will never be triggered because the code in the set `path` has not been changed, the check will never complete.
> > (At least I think that it is the problem here ...)
> 
> I really thought github would be intelligent enough to get that right. We really need to think about splitting gsad and gsa into two separate repos.


I am not sure if this is really the case, but thats the only thing that makes sense to me, because these checks are not running at all ...

Yeah. We really should get that split up done. In the end with a change of the backend we need to get gsad out of gsa anyway, so why not seperate right now.

**Review by y0urself — APPROVED** [review]

**Pull request merged**
