### PR TITLE
Let it work with cmake and cmake3.

### PR DESCRIPTION
**Pull request by tuxmaster5000**
Use the variable for cmake instant of hard coded cmake call.

### CODE REVIEW

**Comment by bjoernricks** [comment]
Thanks!

**Comment by bjoernricks** [comment]
@tuxmaster5000 would like like to be named at the https://github.com/greenbone/gsa/blob/master/CHANGES.md file?

**Comment by tuxmaster5000** [comment]
Hi Björn, yes you can do it.

**Comment by bjoernricks** [comment]
@tuxmaster5000 as tuxmaster5000 or another name? We are using real names for the changes normally.

**Pull request merged**
