### PR TITLE
Refactor CVE Tables to single line table

### PR DESCRIPTION
**Pull request by y0urself**
**What**:

Changing the Tables for CVEs to a one-liner (Name, CVSS BaseVector, Published, Severity, Description).

**Why**:

The old CVE Table format was hard to read and unnecessary complex.

**How**:

Adjusted the Table format.

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

### CODE REVIEW

**Review by bjoernricks — COMMENTED** [review]
Does this consider the CVSSv3 from gvmd already? Is it parsed as cve.cvssBaseVector independent of the CVSS version?

**Comment by y0urself** [comment]
> Does this consider the CVSSv3 from gvmd already? Is it parsed as cve.cvssBaseVector independent of the CVSS version?

No. It parses only CVSSv2 ... I think I need to add a lot of things for CVSSv3 ... should I do that? It wasn't part of the Issue

**Review by sarahd93 — CHANGES_REQUESTED** [review]
Was there a reason for the order of the table columns? Otherwise, I think we should probably use the column order from the jira issue: Name, Description, Published, CVSS, Severity. This feels more consistent with the tables of the other secinfo entities with longer text on the left side and the severity on the right side of the table.

**Review by sarahd93 — APPROVED** [review]
Thank you, this looks really nice!

**Pull request merged**
