### PR TITLE
Add Yarn offline mode option.

### PR DESCRIPTION
**Pull request by tuxmaster5000**
This will be needed, to build it without internet connection.
In this case all needed npm packages can be preloaded into the yarn cache.

### CODE REVIEW

**Comment by tuxmaster5000** [comment]
Modify INSTALLER will fails with:
/bin/sh: /usr/bin/yarn --offline: No such file or directory
Because on COMMAND of add_custom_command.
Arguments must be given as an separate variable.
See:  https://cmake.org/cmake/help/latest/command/add_custom_command.html

**Comment by bjoernricks** [comment]
Ah thanks for the hint! Wasn't aware of that problem yet. In that case your PR is fine and I would only suggest to use `set (YARN_OFFLINE` instead of `set (INSTALLER_ARGS`. `-DYARN_OFFLINE=1` can be kept.

**Comment by tuxmaster5000** [comment]
Ah I understood. This make sense.

**Comment by bjoernricks** [comment]
Looks good. Only the conflict has to be resolved.

**Comment by tuxmaster5000** [comment]
Now it looks good. :)

**Pull request merged**
